/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei";
import { colorPreset, colorPresetIndex } from "../Preset/colorPreset";

function RoomRotating(ref, time) {
  ref.current.rotation.y = Math.cos(time / 6) / 10;
}

function CubeHovering(ref, time) {
  ref.current.rotation.z = -0.2 - (1 + Math.sin(time / 1.5)) / 10;
  ref.current.rotation.x = Math.cos(time / 4) / 8;
  ref.current.rotation.y = Math.sin(time / 4) / 8;
  ref.current.position.y = (1 + Math.sin(time / 1.5)) / 10 - 0.1;
}

function Rotating(ref, time) {
  ref.current.position.x = (1 + Math.sin(time / 1.5)) / 10 - 0.1;
  ref.current.rotation.y = Math.sin(time / 2) / 3;
}

export default function Office() {
  var theme = colorPresetIndex;

  const group = useRef();
  const hovering = useRef();
  const rotating = useRef();

  const { nodes, materials } = useGLTF("models/office_with_material.gltf");

  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    RoomRotating(group, t);
    CubeHovering(hovering, t);
    Rotating(rotating, t);
  });

  return (
    <group ref={group} dispose={null} scale={[1.1, 1.1, 1.1]}>
      {/* Floor */}
      <group dispose={null}>
        <mesh geometry={nodes.bottom_1.geometry}>
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].first}
          />
        </mesh>
      </group>
      {/* Printer */}
      <group dispose={null}>
        <mesh
          geometry={nodes.pinter_1.geometry}
          position={[0.45, 1.17, -1.11]}
          scale={[0.37, 0.35, 0.43]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].seventh}
            metalness={0.2}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Desktop */}
      <group dispose={null}>
        <mesh
          geometry={nodes.coputer_2.geometry}
          position={[0.36, -0.33, -0.26]}
          scale={[0.56, 0.94, 0.15]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].seventh}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Desk */}
      <group dispose={null}>
        <mesh
          material={materials.Material}
          geometry={nodes.desk_1.geometry}
          position={[0.64, 0.81, -0.13]}
          scale={[0.78, 0.78, 0.78]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].first}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Monitor */}
      <group dispose={null}>
        <mesh
          geometry={nodes.computer_1.geometry}
          position={[0.99, 0.78, -0.07]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.44, 0.44, 0.37]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].second}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Tissues */}
      <group dispose={null}>
        <mesh
          geometry={nodes.desk_box_1.geometry}
          position={[0.68, 0.6, 0.74]}
          scale={[0.24, 0.24, 0.24]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].third}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Keyboard */}
      <group dispose={null}>
        <mesh
          geometry={nodes.keyboard_1.geometry}
          position={[0.48, 0.37, -0.01]}
          rotation={[0, 0, -Math.PI]}
          scale={[0.31, 0.56, 0.37]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].second}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Wall Right */}
      <group dispose={null}>
        <mesh
          geometry={nodes.wall_1.geometry}
          position={[-0.35, 0.7, -0.51]}
          scale={[0.44, 0.75, 0.12]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].sixth}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Chair */}
      <group ref={rotating}>
        <mesh
          geometry={nodes.chair_1.geometry}
          position={[-0.18, 0.1, 0.1]}
          rotation={[0, 0.39, 0]}
          scale={[0.53, 0.47, 0.55]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].third}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Wall Left */}
      <group dispose={null}>
        <mesh
          geometry={nodes.wall_2.geometry}
          position={[-0.66, 0.93, -0.3]}
          scale={[0.44, 0.75, 0.04]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].fifth}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* TrashCan */}
      <group dispose={null}>
        <mesh
          geometry={nodes.trashcan_1.geometry}
          position={[0.17, 0.2, 0.79]}
          scale={[0.41, 0.69, 0.41]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].seventh}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Logo */}
      <group dispose={null}>
        <mesh
          geometry={nodes.logo_1.geometry}
          position={[-0.36, 1.06, -0.38]}
          rotation={[0, 0, Math.PI / 2]}
          scale={[0.25, 0.88, 0.71]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].fourth}
            metalness={0.0}
            roughness={0.3}
          />
        </mesh>
      </group>
      {/* Hovering Object */}
      <group ref={hovering} dispose={null}>
        <mesh
          material={materials.Material}
          geometry={nodes.hover_2.geometry}
          position={[-0.02, 1.43, -0.91]}
          scale={[0.09, 0.09, 0.09]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].fourth}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
        <mesh
          material={materials.Material}
          geometry={nodes.hover_1.geometry}
          position={[0.56, 1.83, 0.91]}
          rotation={[2.95, 0.54, -2.78]}
          scale={[0.15, 0.15, 0.15]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].third}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
        <mesh
          material={materials.Material}
          geometry={nodes.hover_3.geometry}
          position={[-0.43, 1.53, 0.85]}
          scale={[0.09, 0.09, 0.09]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].fifth}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
        <mesh
          material={materials.Material}
          geometry={nodes.hover_4.geometry}
          position={[-0.62, 1.24, 0.6]}
          rotation={[-0.94, -1, -1.25]}
          scale={[0.14, 0.14, 0.14]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].sixth}
            metalness={0.0}
            roughness={0.6}
          />
        </mesh>
      </group>
      {/* Cubes */}
      <group dispose={null}>
        <mesh
          material={materials.Material}
          geometry={nodes.graph_1.geometry}
          position={[-0.51, 0.12, 0.85]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].second}
            metalness={0.0}
            roughness={1.0}
          />
        </mesh>
        <mesh
          material={materials.Material}
          geometry={nodes.graph_2.geometry}
          position={[-0.51, 0, 0.69]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].third}
            metalness={0.0}
            roughness={1.0}
          />
        </mesh>
        <mesh
          material={materials.Material}
          geometry={nodes.graph_3.geometry}
          position={[-0.51, 0.11, 0.56]}
        >
          <meshStandardMaterial
            attach="material"
            color={colorPreset[theme].fourth}
            metalness={0.0}
            roughness={1.0}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/office_with_material.gltf");
