/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei";
import { colorPreset, colorPresetIndex } from "../Preset/colorPreset";

function RoomRotating(ref, time) {
  ref.current.rotation.y = (-1 * Math.cos(time / 6)) / 10;
}

function CubeHovering1(ref, time) {
  ref.current.rotation.y = -Math.sin(time / 6) / 4;
  ref.current.position.y = (1 + Math.cos(time / 4)) / 4 + 0.8;
}

function CubeHovering2(ref, time) {
  ref.current.rotation.y = Math.cos(time / 3) / 6;
  ref.current.position.y = (1 + Math.sin(time / 3)) / 5 + 0.8;
}

function CubeHovering3(ref, time) {
  ref.current.rotation.y = Math.sin(time / 4) / 8;
  ref.current.position.y = (1 + Math.sin(time / 5)) / 4 + 0.9;
}

function CubeHovering4(ref, time) {
  ref.current.rotation.y = Math.sin(time / 4) / 4;
  ref.current.position.y = (1 + Math.cos(time / 4)) / 6 + 0.7;
}

function CubeHovering5(ref, time) {
  ref.current.rotation.y = Math.sin(time / 8);
  ref.current.position.y = (1 + Math.sin(time / 6)) / 6 + 0.6;
}

function Rotating(ref, time) {
  ref.current.position.x = (1 + Math.sin(time / 1.5)) / 10 - 0.1;
  ref.current.rotation.y = Math.sin(time / 2) / 3;
}

export default function Weebut(props) {
  var theme = colorPresetIndex;

  const group = useRef();
  const rotating = useRef();
  const hovering1 = useRef();
  const hovering2 = useRef();
  const hovering3 = useRef();
  const hovering4 = useRef();
  const hovering5 = useRef();

  const { nodes, materials } = useGLTF("models/office.gltf");

  useFrame((state) => {
    const t = state.clock.getElapsedTime();
    RoomRotating(group, t);
    Rotating(rotating, t);
    CubeHovering1(hovering1, t);
    CubeHovering2(hovering2, t);
    CubeHovering3(hovering3, t);
    CubeHovering4(hovering4, t);
    CubeHovering5(hovering5, t);
  });

  return (
    <group dispose={null}>
      <group ref={group} {...props} dispose={null} position={[0, -0.2, 0]}>
        {/* Printer */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.pinter_1.geometry}
            position={[1.52, 1.17, -0.66]}
            rotation={[0, -0.96, 0]}
            scale={[0.37, 0.35, 0.43]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].printer}
              metalness={1.0}
              roughness={0.6}
            />
          </mesh>
        </group>
        {/* Desktop */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.coputer_2.geometry}
            position={[0.37, -0.42, -0.33]}
            rotation={[0, -0.96, 0]}
            scale={[0.56, 0.94, 0.15]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].desktop}
              metalness={0.7}
              roughness={0.6}
            />
          </mesh>
        </group>
        {/* Desk */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.desk_1.geometry}
            position={[0.48, 0.75, 0.06]}
            rotation={[0, -0.96, 0]}
            scale={[0.78, 0.78, 0.78]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].desk}
              metalness={0.0}
              roughness={0.6}
            />
          </mesh>
        </group>
        {/* Monitor */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.computer_1.geometry}
            position={[0.59, 0.78, 0.3]}
            rotation={[0, -0.96, -Math.PI / 2]}
            scale={[0.44, 0.44, 0.37]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].monitor}
              metalness={0.8}
              roughness={0.7}
            />
          </mesh>
        </group>
        {/* tissue */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.desk_box_1.geometry}
            position={[-0.19, 0.56, 0.6]}
            rotation={[0, -0.96, 0]}
            scale={[0.24, 0.24, 0.24]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].tissue}
              metalness={0.0}
              roughness={0.6}
            />
          </mesh>
        </group>
        {/* Keyboard */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.keyboard_1.geometry}
            position={[0.24, 0.37, -0.08]}
            rotation={[0, -0.96, -Math.PI]}
            scale={[0.31, 0.56, 0.37]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].keyboard}
              metalness={0.0}
              roughness={0.6}
            />
          </mesh>
        </group>
        {/* Wall Right */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.wall_1.geometry}
            position={[0.17, 0.7, -1.05]}
            rotation={[0, -0.96, 0]}
            scale={[0.44, 0.75, 0.12]}
            castShadow
          >
            <shadowMaterial attach="material" transparent opacity={0.0} />
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].wall_right}
              metalness={0.0}
              roughness={0.6}
            />
          </mesh>
        </group>
        {/* Chair */}
        <group ref={rotating} dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.chair_1.geometry}
            position={[-0.11, 0.1, -0.38]}
            rotation={[0, -0.56, 0]}
            scale={[0.53, 0.47, 0.55]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].chair}
              metalness={0.6}
              roughness={0.6}
            />
          </mesh>
        </group>
        {/* Wall Left */}
        <group dispose={null}>
          <mesh
            material={materials.gray}
            geometry={nodes.wall_2.geometry}
            position={[-0.19, 0.93, -1.19]}
            rotation={[0, -0.96, 0]}
            scale={[0.44, 0.75, 0.04]}
            castShadow
          >
            <shadowMaterial attach="material" transparent opacity={0.0} />
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].wall_left}
              metalness={0.0}
              roughness={0.6}
            />
          </mesh>
        </group>
        {/* Trashcan */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.trashcan_1.geometry}
            position={[-0.6, 0.2, 0.28]}
            rotation={[0, -0.96, 0]}
            scale={[0.41, 0.69, 0.41]}
            castShadow
          >
            <meshPhongMaterial
              attach="material"
              color={colorPreset[theme].trashcan}
              shininess={50}
            />
          </mesh>
        </group>
        {/* Logo */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.logo_1.geometry}
            position={[0.06, 1.06, -0.98]}
            rotation={[0, -0.96, Math.PI / 2]}
            scale={[0.25, 0.88, 0.71]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].logo}
              metalness={0.9}
              roughness={0.5}
            />
          </mesh>
        </group>
        {/* Hover */}
        <group position={[0, 0.8, 0]} dispose={null}>
          <mesh
            ref={hovering2}
            material={materials.Material}
            geometry={nodes.hover_2.geometry}
            position={[1.08, 1.43, -0.93]}
            rotation={[0.16, -1.22, 0.08]}
            scale={[0.09, 0.09, 0.09]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].hover2}
              metalness={0.7}
              roughness={0.6}
            />
          </mesh>

          <mesh
            ref={hovering1}
            material={materials.Material}
            geometry={nodes.hover_1.geometry}
            position={[-0.29, 1.83, 0.75]}
            rotation={[2.81, 1.03, -2.59]}
            scale={[0.15, 0.15, 0.15]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].hover1}
              metalness={0.7}
              roughness={0.6}
            />
          </mesh>

          <mesh
            ref={hovering3}
            material={materials.Material}
            geometry={nodes.hover_3.geometry}
            position={[-0.82, 1.53, -0.09]}
            rotation={[0, -0.96, 0]}
            scale={[0.09, 0.09, 0.09]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].hover3}
              metalness={0.7}
              roughness={0.6}
            />
          </mesh>

          <mesh
            ref={hovering4}
            material={materials.Material}
            geometry={nodes.hover_4.geometry}
            position={[-1.52, 1.24, 0.16]}
            rotation={[-0.52, 0.49, -0.13]}
            scale={[0.14, 0.14, 0.14]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].hover4}
              metalness={0.7}
              roughness={0.6}
            />
          </mesh>
          <mesh
            ref={hovering5}
            material={materials["Material.002"]}
            geometry={nodes.hover_2001.geometry}
            position={[1.33, 0.81, 0.87]}
            rotation={[0, -0.96, 0]}
            scale={[0.09, 0.09, 0.09]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].hover5}
              metalness={0.7}
              roughness={0.6}
            />
          </mesh>
        </group>
        {/* Cube */}
        <group dispose={null}>
          <mesh
            material={materials.Material}
            geometry={nodes.graph_1.geometry}
            position={[-1.09, 0.12, -0.49]}
            rotation={[0, -0.96, 0]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].cube1}
              metalness={0.0}
              roughness={1.0}
            />
          </mesh>

          <mesh
            material={materials.Material}
            geometry={nodes.graph_2.geometry}
            position={[-1.26, 0, -0.37]}
            rotation={[0, -0.96, 0]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].cube2}
              metalness={0.0}
              roughness={1.0}
            />
          </mesh>

          <mesh
            material={materials.Material}
            geometry={nodes.graph_3.geometry}
            position={[-0.86, 0.11, -0.65]}
            rotation={[0, -0.96, 0]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].cube3}
              metalness={0.0}
              roughness={1.0}
            />
          </mesh>
          <mesh
            material={materials["Material.001"]}
            geometry={nodes.graph_1001.geometry}
            position={[-1.45, 0.32, -0.24]}
            rotation={[0, -0.96, 0]}
            castShadow
          >
            <meshStandardMaterial
              attach="material"
              color={colorPreset[theme].cube4}
              metalness={0.0}
              roughness={1.0}
            />
          </mesh>
        </group>
      </group>
      {/* Weebut */}
      <group dispose={null} position={[0, -0.2, 0]}>
        <mesh
          material={materials.textmetarial}
          geometry={nodes.weebut_text.geometry}
          position={[-1.29, 0.53, 0.36]}
          rotation={[Math.PI / 2, 0, 0.01]}
          scale={[0.8, 0.8, 0.8]}
        >
          <meshStandardMaterial
            attach="material"
            color={"#FFFFFF"}
            metalness={0.0}
            roughness={1.0}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("models/office.gltf");
